[package]
name        = "flix-basicdb"
description = "A basic effect-based database interface for Flix using JDBC."
version     = "0.7.0"
flix        = "0.61.1"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/charset-locale"            = "0.9.1"
"github:stephentetley/flix-time"                 = "0.15.0"


[mvn-dependencies]
"org.duckdb:duckdb_jdbc" = "1.3.2.0"
"org.xerial:sqlite-jdbc" = "3.50.3.0"
